export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const START_LOADING_AUTH = 'START_LOADING_AUTH';
export const END_LOADING_AUTH = 'END_LOADING_AUTH';

export const CREATE_ASSET = 'CREATE_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const DELETE_ASSET = 'DELETE_ASSET';
export const FETCH_ALL_ASSETS = 'FETCH_ALL_ASSETS';
export const FETCH_ONE_ASSET = 'FETCH_ONE_ASSET';
export const START_LOADING_ASSETS = 'START_LOADING_ASSETS';
export const END_LOADING_ASSETS = 'END_LOADING_ASSETS';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const START_LOADING_USERS = 'START_LOADING_USERS';
export const END_LOADING_USERS = 'END_LOADING_USERS';

export const GET_ERRORS = 'GET_ERRORS';