import type { NextPage } from 'next'
import Head from 'next/head'

import styles from './index.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Dashboard</h1>
    </>
  )
}

export default Home
