import type { NextPage } from 'next'
import Head from 'next/head'
import { trpc } from '@utils/trpc'

const Home: NextPage = () => {
  const utils = trpc.useContext()
  const addAsset = trpc.useMutation('asset.add', {
    async onSuccess() {
      await utils.invalidateQueries(['asset.getAll'])
    }
  })
  const addRoom = trpc.useMutation('room.add')

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <button
        onClick={async (e) => {
          e.preventDefault()

          await addRoom.mutateAsync({
            name: '114'
          })
        }}
      >
        Add Room
      </button>
      <button
        onClick={async (e) => {
          e.preventDefault()

          await addAsset.mutateAsync({
            location: '114',
            data: {
              tagNumber: 'C12345',
              description: 'A piece of Yamaha hardware.',
              make: 'Yamaha',
              model: 'Model',
              type: 'hardware',
              minimumAccessLevel: 'staff',
              status: 'in'
            }
          })
        }}
      >
        Add Asset
      </button>
    </>
  )
}

export default Home
